// Generated by dts-bundle v0.7.3

declare module 'shftjs' {
    import { drag } from 'shftjs/drag';
    import { drop } from 'shftjs/drop';
    import { is, matches, clear } from 'shftjs/util';
    function defaultmove(e: DragEvent): void;
    const _default: {
        drag: typeof drag;
        drop: typeof drop;
        util: {
            clear: typeof clear;
            defaultmove: typeof defaultmove;
            is: typeof is;
            matches: typeof matches;
        };
    };
    export default _default;
}

declare module 'shftjs/drag' {
    export function drag(el: Element): void;
}

declare module 'shftjs/drop' {
    export function drop(el: any, options?: {
        accepts?: string;
        overlap?: number;
    }): void;
}

declare module 'shftjs/util' {
    export function clamp(value: number, min?: number, max?: number): number;
    export function matches(el: Element, selectors?: string | string[]): boolean;
    export function overlapPct(el: Element, other: Element): number;
    export function is(el: Element, type?: 'drag' | 'drop' | 'draggable' | 'droppable' | null): boolean;
    export function clear(el: any): void;
    export function canDrop(droppable: Element, dragged: Element): boolean;
}

